### ISSUE TITLE
knife 14

### ISSUE THREAD

**Issue by robuye** [johnbarney/docker-knife#2]
Hey John,

First of all thanks for setting up this docker image, it's really cool you maintain and keep it up to date.

The `latest` ships with chef & knife 14 (it was released just this month) and there are breaking changes.

I have switched to a "proper" tag now myself, but I think it may be worth adding a `14` tag on the Dockerhub so people can start using it without relying on `latest`.

Thanks again!

Rob

**Comment by johnbarney** [comment]
I will make time to attend to this. Thanks for letting me know.

**Comment by johnbarney** [comment]
Thank you for the feedback. Tag 14 created. Let me know if you have any more issues.

**Comment by robuye** [comment]
Thank you, much appreciated!
